# Importing modules
import random

# Country Function

def countries(word):
    dic = [
        "AFGHANISTAN",
        "ALBANIA",
        "ALGERIA",
        "ANDORRA",
        "ANGOLA",
        "ANTIGUA AND BARBUDA",
        "ARGENTINA",
        "ARMENIA",
        "AUSTRALIA",
        "AUSTRIA",
        "AZERBAIJAN",
        "BAHAMAS",
        "BAHRAIN",
        "BANGLADESH",
        "BARBADOS",
        "BELARUS",
        "BELGIUM",
        "BELIZE",
        "BENIN",
        "BHUTAN",
        "BOLIVIA",
        "BOSNIA AND HERZEGOVINA",
        "BOTSWANA",
        "BRAZIL",
        "BRUNEI",
        "BULGARIA",
        "BURKINA FASO",
        "BURUNDI",
        "COTE DLVOIRE",
        "CABO VERDE",
        "CAMBODIA",
        "CAMEROON",
        "CANADA",
        "CENTRAL AFRICAN REPUBLIC"
        "CHAD",
        "CHILE",
        "CHINA",
        "COLOMBIA",
        "COMOROS",
        "CONGO",
        "CROATIA",
        "CUBA",
        "CYPRUS",
        "CZECHIA",
        "DENMARK",
        "DJIBOUTI",
        "DOMINICA",
        "ECUADOR",
        "EGYPT",
        "ERITREA",
        "ESTONIA",
        "ESWATINI",
        "ETHIOPIA",
        "FIJI",
        "FINLAND",
        "FRANCE",
        "GABON",
        "GAMBIA",
        "GEORGIA",
        "GERMANY",
        "GHANA",
        "GREECE",
        "GRENADA",
        "GUATEMALA",
        "GUINEA",
        "GUINEA-BISSAU",
        "GUYANA",
        "HAITI",
        "HOLY SEE",
        "HONDURAS",
        "HUNGARY",
        "ICELAND",
        "INDIA",
        "INDONESIA",
        "IRAN",
        "IRAQ",
        "IRELAND",
        "ISRAEL",
        "ITALY",
        "JAMAICA",
        "JAPAN",
        "JORDAN",
        "KAZAKHSTAN",
        "KENYA",
        "KIRIBATI",
        "KUWAIT",
        "KYRGYZSTAN",
        "LAOS",
        "LATVIA",
        "LEBANON",
        "LESOTHO",
        "LIBERIA",
        "LIBYA",
        "LIECHTENSTEIN",
        "LITHUANIA",
        "LUXEMBOURG",
        "MADAGASCAR",
        "MALAWI",
        "MALAYSIA",
        "MALDIVES",
        "MALI",
        "MALTA",
        "MARSHALL ISLANDS",
        "MAURITANIA",
        "MEXICO",
        "MICRONESIA",
        "MONACO",
        "MONGOLIA",
        "MONTENEGRO",
        "MOROCCO",
        "MOZAMBIQUE",
        "MYANMAR",
        "NAMIBIA",
        "NAURU",
        "NEPAL",
        "NETHERLANDS"
        "NEW ZEALAND",
        "NICARAGUA",
        "NIGER",
        "NIGERIA",
        "NORTH KOREA",
        "NORTH MACEDONIA",
        "NORWAY",
        "OMAN",
        "PAKISTAN",
        "PALAU",
        "PALESTINE STATE",
        "PANAMA",
        "PAPUA NEW GUINEA",
        "PARAGUAY",
        "PERU",
        "PHILIPPINES",
        "POLAND",
        "PORTUGAL",
        "QATAR",
        "ROMANIA",
        "RUSSIA",
        "RWANDA",
        "SAINT KITTS AND NEVIS",
        "SAINT LUCIA",
        "SAMOA",
        "SAN MARINO",
        "SAO TOME AND PRINCIPE",
        "SENEGAL",
        "SERBIA",
        "SEYCHELLES",
        "SIERRA LEONE",
        "SINGAPORE",
        "SLOVAKIA",
        "SLOVENIA",
        "SOLOMON ISLANDS",
        "SOMALIA",
        "SOUTH AFRICA",
        "SOUTH KOREA",
        "SOUTH SUDAN",
        "SUDAN",
        "SPAIN",
        "SURINAME",
        "SWEDEN",
        "SWITZERLAND",
        "SYRIA",
        "TAJIKISTAN",
        "TANZANIA",
        "THAILAND",
        "TOGO",
        "TONGA",
        "TRINIDAD AND TOBAGO",
        "TIMOR LESTE",
        "TUNISIA",
        "TURKEY",
        "TURKMENISTAN",
        "TUVALU",
        "UGANDA",
        "UKRAINE",
        "UNITED ARAB EMIRATES",
        "UNITED KINGDOM",
        "UNITED STATES OF AMERICA",
        "URUGUAY",
        "UZBEKISTAN",
        "VANUATU",
        "VENEZUELA",
        "VIETNAM",
        "YEMEN",
        "ZAMBIA",
        "ZIMBABWE",
    ]

    word = random.choice(dic)

    return word