# Importing random
import random

# Fruit and Vegetable function

def fruitsVegetables(word):
    fruit = [
        "ACELORA",
        "APPLE",
        "APRICOT",
        "AVOCADO",
        "BANANA",
        "BLACKBERRY ",
        "BLACKCURRANT",
        "BLUEBERRY",
        "BREADFRUIT",
        "CANTALOUPE",
        "CARAMBOLA",
        "CHERIMOYA",
        "CHERRIES",
        "CLEMENTINE",
        "COCONUT",
        "CRANBERRY",
        "CUSTARD APPLE",
        "DATE FRUIT",
        "DRAGON FRUIT",
        "DURIAN",
        "ELDERBERRY",
        "FEIJOA",
        "FIG",
        "GOOSEBERRY",
        "GRAPEFRUIT",
        "GRAPE",
        "GUAVA",
        "HONEYDEW",
        "JACKFRUIT",
        "JAVA PLUM",
        "JUJUBE FRUIT",
        "KIWI",
        "KUMQUAT",
        "LEMON",
        "LIME",
        "LONGAN",
        "LOQUAT",
        "LYCHEE",
        "MANDARIN",
        "MANGO",
        "MANGOSTEEN",
        "MULBERRY",
        "NECTARINE",
        "OLIVE",
        "ORANGE",
        "PAPAYA",
        "PEACH",
        "PEAR",
        "PERSIMMON",
        "PINEAPPLE",
        "PITANGA",
        "POMEGRANATE",
        "PRICKLY PEAR",
        "PRUNE",
        "PUMMELO",
        "QUINCE",
        "RASPBERRY",
        "RHUBARB",
        "ROSE APPLE",
        "SAPODILLA",
        "SAPOTE",
        "SOURSOP",
        "STRAWBERRY",
        "SUGAR APPLE",
        "TAMARIND",
        "TANGERINE",
        "WATERMELON"
    ]

    vegetable = [
        "AMARANTH LEAVES",
        "ARROWROOT",
        "ARTICHOKE",
        "ARUGALA",
        "ASPARAGUS",
        "BAMBOO",
        "BEAN",
        "BEETROOT",
        "BELGIAN ENDIVE",
        "BITTER MELON",
        "BOK CHOY",
        "BROADBEAN",
        "BRUSSEL SPROUTS",
        "BROCCOLI",
        "GREEN CABBAGE",
        "RED CABBAGE",
        "CARROT",
        "CASSAVA",
        "CAULIFLOWER",
        "CELERIAC",
        "CELERY",
        "CHAYOTE",
        "CHICORY",
        "COLLARDS",
        "CORN",
        "CROOKNECK",
        "CUCUMBER",
        "DAIKON",
        "DANDELION",
        "SOYBEAN",
        "EGGPLANT",
        "FENNEL",
        "FIDDLEHEAD",
        "GINGER",
        "HORSERADISH",
        "JICAMA",
        "KALE",
        "KOHLRABI",
        "LEEK",
        "LETTUCE",
        "MUSHROOM",
        "OKRA",
        "ONION",
        "PARSNIP",
        "PEA",
        "PEPPER",
        "POTATO",
        "PUMPKIN",
        "RADICCHIO",
        "RADISH",
        "RUTABAGA",
        "SALSIFY",
        "SHALLOT",
        "SORREL",
        "SQUASH",
        "SPINACH",
        "TOMATILLO",
        "TOMATO",
        "TURNIP",
        "WATERCRESS",
        "YAM",
        "ZUCCHINI"
    ]

    randomDic = random.randint(1, 3)

    if randomDic == 1:
        word = random.choice(fruit)
        return word
    else:
        word = random.choice(vegetable)
        return word
