# Importing random
import random

# Car Function

def car(word):
    dic = [
        "ACURA",
        "ALFA ROMEO",
        "AUDI",
        "ALPINA",
        "ASTON MARTIN",
        "BENTLEY",
        "BMW",
        "BUGATTI",
        "BUICK",
        "CADILLAC",
        "CHEVROLET",
        "CHERY",
        "CHRYSLER",
        "CITROEN",
        "DACIA",
        "DS",
        "DODGE",
        "FERRARI",
        "FIAT",
        "FORD",
        "GEELY",
        "GMC",
        "GREAT WALL",
        "HONDA",
        "HYUNDAI",
        "INFINITI",
        "JAGUAR",
        "JEEP",
        "KIA",
        "KOENIGSEGG",
        "LAMBORGHINI",
        "LEXUS",
        "LOTUS",
        "LINCOLN",
        "LAND ROVER",
        "MASERATI",
        "MAZDA",
        "MCLAREN",
        "MERCEDES BENZ",
        "MG",
        "MINI",
        "MITSUBISHI",
        "MORGAN",
        "NISSAN",
        "OPEL",
        "PAGANI",
        "PEUGEOT",
        "PORSCHE",
        "PROTON",
        "PERODUA",
        "RAM",
        "RENAULT",
        "ROLLS ROYCE",
        "SAAB",
        "SEAT",
        "SKODA",
        "SMART",
        "SSANGYONG",
        "SUBARU",
        "SUZUKI",
        "TESLA",
        "TOYOTA",
        "VAUXHALL",
        "VOLKSWAGEN",
        "VOLVO"
    ]

    word = random.choice(dic)

    return word
