# Importing random
import random

# Harry Potter Spells
def Harry_Potter_Spells(word):
    dic = [
        "ALBERTO",
        "ACCIO",
        "AGUAMENTI",
        "ALARTE ASCENDARE",
        "ALOHOMORA",
        "AMATO ANIMO ANIMATO ANIMAGUS",
        "ANAPNEO",
        "ANTEOCULATIA",
        "APARECIUM",
        "APPARE VESTIGIUM",
        "AQUA ERUCTO",
        "ARANIA EXUMAI",
        "ARRESTO MOMENTUM",
        "ASCENDIO",
        "AVADA KEDAVRA",
        "AVIFORS",
        "AVENSEGUIM",
        "AVIS",
        "BAUBILLIOUS",
        "BOMBARDA",
        "BOMBARDA MAXIMA",
        "BRACKIUM EMENDO",
        "CALVORIO",
        "CANTIS",
        "CAPACIOUS EXTREMIS",
        "CARPE RETRACTUM",
        "CAVE INIMICUM",
        "CIRCUMROTA",
        "CISTEM APERIO",
        "COLLOPORTUS",
        "COLLOSHOO",
        "COLOVARIA",
        "CONFRINGO",
        "CONFUNDO",
        "CRINUS MUTO",
        "CRUCIO",
        "DEFODIO",
        "DELETRIUS",
        "DENSAUGEO",
        "DEPRIMO",
        "DEPULSO",
        "DESCENDO",
        "DIFFINDO",
        "DIMINUENDO",
        "DISSENDIUM",
        "DRACONIFORS",
        "DURO",
        "EBUBLIO",
        "ENGORGIO",
        "ENGORGIO SKULLUS",
        "ENTOMORPHIS",
        "EPISKEY",
        "EPOXIMISE",
        "ERECTO",
        "EVANESCE",
        "EVANESCO",
        "EVERTE STATUM",
        "EXPECTO PATRONUM",
        "EXPELLIARMUS",
        "EXPULSO",
        "FERULA",
        "FIANTO DURI",
        "FIENDFYRE",
        "FINESTRA",
        "FINITE INCANTATEM",
        "FLAGRANTE",
        "FLINTIFORS",
        "FLIPENDO",
        "FLIPENDO DUO",
        "FLIPENDO TRIA",
        "FUMOS",
        "FUMOS DUO",
        "FURNUNCULUS",
        "GEMINIO",
        "GLACIUS",
        "GLACIUS DUO",
        "GLACIUS TRIA",
        "GLISSEO",
        "HARONIA NECTERE PASSUS",
        "HERBIFORS",
        "HERBIVICUS",
        "HOMENUM REVELIO",
        "HOMONCULOUS",
        "HOMORPHUS",
        "ILLEGIBILUS",
        "IMMOBULUS",
        "IMPENDIMENTA",
        "IMPERIO",
        "IMPERVIUS",
        "INANIMATUS CONJURUS",
        "INCARCEROUS",
        "INECENDIO",
        "INCENDIO DUO",
        "INCENDIO TRIA",
        "INFLATUS",
        "INFORMOUS",
        "LOCOMOTOR WIBBLY",
        "LACARNUM INFLAMARI",
        "LEGILIMENS",
        "LEVICORPUS",
        "LIBERACORPUS",
        "LOCOMOTOR",
        "LOCOMOTOR MORTIS",
        "LUMOS",
        "LUMOS DUO",
        "LUMOS MAXIMA",
        "LUMOS SOLEM",
        "METEOLOJINX RECANTO",
        "MIMBLEWIMBLE",
        "MOBILIARBUS",
        "MOBILICORPUS",
        "MOLLIARE",
        "MORSMODRE",
        "MUCUS AD NAUSEAM",
        "MUFLIATO",
        "MULICORFORS",
        "MUTATIO SKULLUS",
        "NOX",
        "NEBULUS",
        "OCULUS REPARO",
        "OBLIVIATE",
        "OBSCURO",
        "OPPUGNO",
        "ORBIS",
        "ORCHIDEOUS",
        "OSCAUSI",
        "PAPYRUS REPARO",
        "PARTIS TEMPORUS",
        "PERICULUM",
        "PESKIPIKSI PESTERNOMI",
        "PETRIFICUS TOTALUS",
        "PIERTOTUM LOCOMOTOR",
        "PISCIFORS",
        "PORTUS",
        "PRIOR INCANTATO",
        "PROTEGO",
        "PROTEGO DIABOLICA",
        "PROTEGO HORRIBILIS",
        "PROTEGO MAXIMA",
        "PROTEGO TOTALUM",
        "QUIETUS",
        "REDACTUM SKULLUS",
        "REDUCIO",
        "REDUCTO",
        "REPARIFORS",
        "REVERTE",
        "RELASHIO",
        "RENNERVATE",
        "REPARIFARGE",
        "REPARO",
        "REPELLO MUGGLETUM",
        "REPELLO INIMICUM",
        "REVELIO",
        "RICTUSEMPRA",
        "RIDDIKULUS",
        "SALVIO HEXIA",
        "SCOURGIFY",
        "SECTUMSEMPRA",
        "SERPENSORTIA",
        "SILENCIO",
        "SKURGE",
        "SLUGULUS ERECTO",
        "SONORUS",
        "SPECIALIS REVELIO",
        "SPONGIFY",
        "STERNIUS",
        "STUPEFY",
        "SURGITO",
        "TARANTALLEGRA",
        "TURGEO",
        "TITILLANDO",
        "VENTUS",
        "VENTUS DUO",
        "VERA VENTO",
        "VERDILLIOUS",
        "VERDIMILLIOUS",
        "VERDIMILLIOUS DUO",
        "VERMICULUS",
        "VERMILLIOUS",
        "VIPERA EVANESCA",
        "VULNERA SANENTUR",
        "WADDIWASI",
        "WINGARDIUM LEVIOSA",
    ]

    word = random.choice(dic)

    return word
